### ISSUE TITLE
Multiple color schemes...

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/api.dart.dev#57]
Would be nice to be able to switch to a "dark" mode without using plugins.  Small [stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) example:

``` css
body {
  background: #202020;
  color: #d0d0d0;
}

.sidebar {
  background: #606060;
}

.sidebar a {
  color: rgb(182, 182, 182);
}

section.summary h2,
.signature,
dd {
  color: rgb(190, 190, 190);  
}

code {
  background: #404040;
}
```
